easy_admin:
    entities:
        # List the entity class name you want to manage
        Tournament:
            class: App\Entity\Tournament
            list:
                    fields: ['id', {property: 'link', type: 'url'}, 'description', { property: 'startTimestamp', type: 'datetime', format: 'd/m/Y H:i:s'  }, 'place']


            form:
                fields:
                    - title
                    - description
                    - { property: 'startTimestamp', type: datetime, type_options: { input: timestamp, widget: choice }} 
                    - { property: 'endTimestamp', type: datetime, type_options: { input: timestamp, widget: choice }}
                    - place
                    - placeGpsX
                    - placeGpsY
                    - { property: 'pairingSystem', type: choice,  type_options: { choices: { SWISS: 2, ROUND: 1 }}}
                    - numberOfRounds
                    - { property: 'status', type: choice, type_options: { choices: { New: 0, inProgress: 1, Completed: 2 }}}
        Player:
            class: App\Entity\Player
            list:
                fields: ['id', 'firstName', 'fathersName', 'lastName', 'avatarSrc', 'gender', 'birthDate']
            form:
                fields:
                     - firstName
                     - fathersName
                     - lastName
                     - avatarSrc
                     - { property: 'gender', type: choice, type_options: { choices: { Male: 0, Female: 1 }}}
                     - { property: 'birthDate', type: birthday }
                     - { property: 'range', type: choice, type_options: { choices: { 3_ROZRYAD: 0,  2_ROZRYAD : 1, 1_ROZRYAD : 2, KMS : 3, MS: 4, GM: 5 }}}
                     - city        
                     - federation
                     - { property: 'phone', type: 'text'}
                     - { property: 'email', type: 'email'}
