easy_admin:
    entities:
        # List the entity class name you want to manage
        Tournament:
            class: App\Entity\Tournament
            list:
                    fields: ['id', 'title', 'description', 'startTimestamp', 'place']
            form:
                fields:
                    - title
                    - description
                    - {property: 'startTimestamp', type: datetime}
                    - endTimestamp
                    - place
                    - placeGpsX
                    - placeGpsY
                    - pairingSystem
                    - numberOfRounds
                    - {property: 'status', type: choice, type_options: {choices: {New: 0,inProgress: 1}}}
        Player:
            class: App\Entity\Player
            list:
                fields: ['id', 'firstName', 'fathersName', 'lastName', 'avatarSrc', 'gender', 'birthDate']
            form:
                fields:
                     - firstName
                     - fathersName
                     - lastName
                     - avatarSrc
                     - gender
                     - birthDate
                     - range
                     - city
                     - federation
                     - phone
                     - email

