easy_admin:
    site_name: '<strong>Турніри з шашок</strong>'
    list:
        title: '%%entity_label%%'
    entities:
        Tournament:
            class: App\Entity\Tournament
            list:
                actions:
                    - { name: 'new', label: 'New tournament' }
                    - { name: 'search', label: 'Search' }
                    - { name: 'edit', label: 'Edit' }
                    - { name: 'delete', label: 'Delete' }
                fields: ['Id', {property: 'link', label: 'Link', type: 'url'}, 'description', { property: 'startTimestamp', label: 'Start Timestamp', type: 'datetime', format: 'd/m/Y H:i:s'  }, 'place']
            form:
                actions:
                    - { name: 'delete', label: 'Delete' }
                    - { name: 'list', label: 'List' }
                fields:
                    - title
                    - description
                    - { property: 'startTimestamp', label: 'Start Timestamp', type: datetime, type_options: { input: timestamp, widget: choice }}
                    - { property: 'endTimestamp', label: 'End Timestamp', type: datetime, type_options: { input: timestamp, widget: choice }}
                    - place
                    - { property: 'placeGpsX', label: 'Place GpsX' }
                    - { property: 'placeGpsY', label: 'Place GpsY' }
                    - { property: 'pairingSystem', type: choice,  type_options: { choices: { SWISS: 0, ROUND: 1 }}}
                    - numberOfRounds
                    - { property: 'status', type: choice, type_options: { choices: { New: 0, inProgress: 1, Completed: 2 }}}
            new:
                title: 'Create tournament'
            edit:
                title: 'Edit tournament'
        Player:
            class: App\Entity\Player
            list:
                actions:
                    - { name: 'new', label: 'New player' }
                    - { name: 'search', label: 'Search' }
                    - { name: 'edit', label: 'Edit' }
                    - { name: 'delete', label: 'Delete' }
                fields: ['Id', 'firstName', 'fathersName', 'lastName', 'avatarSrc', 'gender', 'birthDate']
            form:
                actions:
                    - { name: 'delete', label: 'Delete' }
                    - { name: 'list', label: 'List' }
                fields:
                     - firstName
                     - fathersName
                     - lastName
                     - avatarSrc
                     - { property: 'gender', type: choice, type_options: { choices: { Male: 0, Female: 1 }}}
                     - { property: 'birthDate', type: birthday }
                     - { property: 'range', type: choice, type_options: { choices: { 3_ROZRYAD: 0,  2_ROZRYAD : 1, 1_ROZRYAD : 2, KMS : 3, MS: 4, GM: 5 }}}
                     - city        
                     - federation
                     - { property: 'phone', type: 'text'}
                     - { property: 'email', type: 'email'}
            new:
                title: 'Create player'
            edit:
                title: 'Edit player'

