easy_admin_bundle:
    resource: '@EasyAdminBundle/Controller/AdminController.php'
    prefix: /admin
    type: annotation

add_players_tournament:
    path: admin/tournament/{id}
    controller: App\Controller\Admin\TournamentController::addPlayersTournamentAction

delete_player_tournament:
    path: admin/tournament/delete_player/{participantId}
    controller: App\Controller\Admin\TournamentController::deletePlayerTournamentAction

set_tournament_results:
    path: admin/tournament/set_tournament_results/{tournamentId}
    controller: App\Controller\Admin\TournamentController::setSwissTournamentResultsAction

set_round_results:
    path: admin/tournament/set_round_results/{tournamentId}/{roundId}
    controller: App\Controller\Admin\TournamentController::setSwissRoundResultsAction




