easy_admin_bundle:
    resource: '@EasyAdminBundle/Controller/AdminController.php'
    prefix: /admin
    type: annotation

add_players_tournament:
    path: admin/tournament/{id}
    controller: App\Controller\Admin\TournamentController::addPlayersTournamentAction

delete_player_tournament:
    path: admin/tournament/delete_player/{participantId}
    controller: App\Controller\Admin\TournamentController::deletePlayerTournamentAction

set_tournament_results:
    path: admin/tournament/set_tournament_results/{tournamentId}
    controller: App\Controller\Admin\TournamentController::setSwissTournamentResultsAction

round_system_tournament_results:
    path: admin/tournament/{id}/round_system/results
    controller: App\Controller\Admin\TournamentController::getTournamentResultsForRoundSystemAction

set_round_result:
    path: admin/{participantOneId}/{participantTwoId}
    controller: App\Controller\Admin\TournamentController::setResultsForRoundSystemAction





