index:
    path: /
    controller: App\Controller\MainController::index

show_tournaments:
    path: /tournaments/{statusSlug}
    controller: App\Controller\MainController::showAllTournamentsAction
    defaults:
        statusSlug: 'all'

round_generation:
    path: /admin/tournament/{id}/generate
    controller:  App\Controller\Admin\TournamentController::generatePairsAction